Script started on 2015年03月10日 (週二) 17時50分58秒
]0;H24031134@2015cpp: ~H24031134@2015cpp:~$ ls
lab1.script
]0;H24031134@2015cpp: ~H24031134@2015cpp:~$ whoami; pwd
H24031134
/home/H24031134
]0;H24031134@2015cpp: ~H24031134@2015cpp:~$ git config -1[Kl;[K
user.name=bmw2142
user.email=bmw2142@gmail.com
]0;H24031134@2015cpp: ~H24031134@2015cpp:~$ git config -l[2Pwhoami; pwdls[Kgit clone https://github.com/<bmw2142@gmail.com>/lab1.git[C[C[C[C[C[C[C[C[1Pgmail.com>/lab1.git[1Pmail.com>/lab1.git[1Pail.com>/lab1.git[1Pil.com>/lab1.git[1Pl.com>/lab1.git[1P.com>/lab1.git[1Pcom>/lab1.git[1Pom>/lab1.git[1Pm>/lab1.git[1P>/lab1.git
bash: bmw2142: No such file or directory
]0;H24031134@2015cpp: ~H24031134@2015cpp:~$ git clone https://github.com/<bmw2142>/lab1.git[C
bash: bmw2142: No such file or directory
]0;H24031134@2015cpp: ~H24031134@2015cpp:~$ git clone https://github.com/<bmw2142>/lab1.git
bash: bmw2142: No such file or directory
]0;H24031134@2015cpp: ~H24031134@2015cpp:~$ exit

Script done on 2015年03月10日 (週二) 17時52分46秒
